# Generated by Django 3.0.7 on 2020-07-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='質問内容')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Student', verbose_name='質問者')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Subject', verbose_name='科目')),
            ],
            options={
                'verbose_name': 'Question Table',
                'verbose_name_plural': '質問テーブル',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='回答内容')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Question', verbose_name='質問')),
                ('ta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Student', verbose_name='回答者(TA)')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Teacher', verbose_name='回答者(教員)')),
            ],
            options={
                'verbose_name': 'Answer Table',
                'verbose_name_plural': '回答テーブル',
                'db_table': 'answer',
            },
        ),
    ]
