# Generated by Django 3.0.7 on 2020-07-05 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ta',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='question',
            name='student',
        ),
        migrations.AddField(
            model_name='answer',
            name='answerer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='回答者'),
        ),
        migrations.AddField(
            model_name='question',
            name='questioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='質問者'),
        ),
    ]
