# Generated by Django 3.0.7 on 2020-07-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200705_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='タグ'),
        ),
    ]
