# Generated by Django 3.0.7 on 2020-08-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_question_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(to='post.Tag', verbose_name='タグ'),
        ),
    ]
