PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO auth_permission VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO auth_permission VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO auth_permission VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO auth_permission VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO auth_permission VALUES(5,2,'add_permission','Can add permission');
INSERT INTO auth_permission VALUES(6,2,'change_permission','Can change permission');
INSERT INTO auth_permission VALUES(7,2,'delete_permission','Can delete permission');
INSERT INTO auth_permission VALUES(8,2,'view_permission','Can view permission');
INSERT INTO auth_permission VALUES(9,3,'add_group','Can add group');
INSERT INTO auth_permission VALUES(10,3,'change_group','Can change group');
INSERT INTO auth_permission VALUES(11,3,'delete_group','Can delete group');
INSERT INTO auth_permission VALUES(12,3,'view_group','Can view group');
INSERT INTO auth_permission VALUES(13,4,'add_user','Can add user');
INSERT INTO auth_permission VALUES(14,4,'change_user','Can change user');
INSERT INTO auth_permission VALUES(15,4,'delete_user','Can delete user');
INSERT INTO auth_permission VALUES(16,4,'view_user','Can view user');
INSERT INTO auth_permission VALUES(17,5,'add_contenttype','Can add content type');
INSERT INTO auth_permission VALUES(18,5,'change_contenttype','Can change content type');
INSERT INTO auth_permission VALUES(19,5,'delete_contenttype','Can delete content type');
INSERT INTO auth_permission VALUES(20,5,'view_contenttype','Can view content type');
INSERT INTO auth_permission VALUES(21,6,'add_session','Can add session');
INSERT INTO auth_permission VALUES(22,6,'change_session','Can change session');
INSERT INTO auth_permission VALUES(23,6,'delete_session','Can delete session');
INSERT INTO auth_permission VALUES(24,6,'view_session','Can view session');
INSERT INTO auth_permission VALUES(25,7,'add_student','Can add Student Master');
INSERT INTO auth_permission VALUES(26,7,'change_student','Can change Student Master');
INSERT INTO auth_permission VALUES(27,7,'delete_student','Can delete Student Master');
INSERT INTO auth_permission VALUES(28,7,'view_student','Can view Student Master');
INSERT INTO auth_permission VALUES(29,8,'add_teacher','Can add Teacher Master');
INSERT INTO auth_permission VALUES(30,8,'change_teacher','Can change Teacher Master');
INSERT INTO auth_permission VALUES(31,8,'delete_teacher','Can delete Teacher Master');
INSERT INTO auth_permission VALUES(32,8,'view_teacher','Can view Teacher Master');
INSERT INTO auth_permission VALUES(33,9,'add_subject','Can add Subject Master');
INSERT INTO auth_permission VALUES(34,9,'change_subject','Can change Subject Master');
INSERT INTO auth_permission VALUES(35,9,'delete_subject','Can delete Subject Master');
INSERT INTO auth_permission VALUES(36,9,'view_subject','Can view Subject Master');
INSERT INTO auth_permission VALUES(37,10,'add_question','Can add Question Table');
INSERT INTO auth_permission VALUES(38,10,'change_question','Can change Question Table');
INSERT INTO auth_permission VALUES(39,10,'delete_question','Can delete Question Table');
INSERT INTO auth_permission VALUES(40,10,'view_question','Can view Question Table');
INSERT INTO auth_permission VALUES(41,11,'add_answer','Can add Answer Table');
INSERT INTO auth_permission VALUES(42,11,'change_answer','Can change Answer Table');
INSERT INTO auth_permission VALUES(43,11,'delete_answer','Can delete Answer Table');
INSERT INTO auth_permission VALUES(44,11,'view_answer','Can view Answer Table');
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
COMMIT;
